routes = [["tg#329682887", "ts3#69"]]

[proto]
    [proto.telegram]

    [proto.teamspeak]
    host = "ts.segfault.party"
    port = 10022

[instances]
    [instances.tg]
    proto = "telegram"
    bot_token = "1038119296:AAH7-ZERtVFBZCJAAhdv-Nz0tdW8Se5aaoI"
    api_id = 96668
    api_hash = "71a1f7c3cb65c05aece46c1a5ae04f0c"

    [instances.ts3]
    proto = "ts3-serverquery"
    sq_user = 'serveradmin'
    sq_password = 'kaas'
    sq_host = 'ts.segfault.party'
    sq_port = 10011
