[project]
name = "tsbridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sam van Kampen", email = "sam@tehsvk.net" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "aiorun>=2025.1.1",
    "coloredlogs>=15.0.1",
    "docopt>=0.6.2",
    "protobuf>=6.32.0",
    "requests>=2.32.4",
    "telethon<=1.16.2",
]

[project.scripts]
bridge = "bridge:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "types-docopt>=0.6.11.20241107",
    "types-protobuf>=6.30.2.20250822",
    "types-requests>=2.32.4.20250809",
]

[tool.hatch.build.targets.wheel]
packages = ["src/bridge"]
