[tool.poetry]
name = "bridge"
version = "0.1.0"
description = ""
authors = ["Sam van Kampen <sam@tehsvk.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
docopt = "^0.6.2"
aiohttp = "^3.9.3"
Telethon = "1.16.2"
aiorun = "^2023.7.2"
coloredlogs = "^15.0.1"
requests = "^2.31.0"

[tool.poetry.scripts]
bridge = "bridge:main"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
types-docopt = "^0.6.11.4"
types-requests = "^2.31.0.20240218"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
